### ISSUE TITLE
Cant seem to install pywarping

### ISSUE THREAD

**Issue by SG-SakethGupta** [dopevog/pywarping#1]
This is the error when I try to install it with pip(Pip version 21.1.2, python version 3.9.1)

`Collecting pywarping
  Using cached pywarping-0.2-py3-none-any.whl
Requirement already satisfied: scikit-image in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from pywarping) (0.18.2)
Requirement already satisfied: opencv-python in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from pywarping) (4.5.2.52)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from pywarping) (3.4.2)
Collecting dlib
  Using cached dlib-19.22.0.tar.gz (7.4 MB)
Requirement already satisfied: click>=7.0 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from pywarping) (7.1.2)
Requirement already satisfied: numpy>=1.16.4 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from pywarping) (1.20.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=2.0.0->pywarping) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=2.0.0->pywarping) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=2.0.0->pywarping) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=2.0.0->pywarping) (8.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from matplotlib>=2.0.0->pywarping) (2.8.1)
Requirement already satisfied: six in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from cycler>=0.10->matplotlib>=2.0.0->pywarping) (1.15.0)
Requirement already satisfied: networkx>=2.0 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from scikit-image->pywarping) (2.5.1)
Requirement already satisfied: scipy>=1.0.1 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from scikit-image->pywarping) (1.6.3)
Requirement already satisfied: imageio>=2.3.0 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from scikit-image->pywarping) (2.9.0)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from scikit-image->pywarping) (2021.6.14)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from scikit-image->pywarping) (1.1.1)
Requirement already satisfied: decorator<5,>=4.3 in c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages (from networkx>=2.0->scikit-image->pywarping) (4.4.2)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\saketh\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\setup.py'"'"'; __file__='"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\saketh\AppData\Local\Temp\pip-wheel-3lg422aj'
       cwd: C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\
  Complete output (58 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\build\lib.win-amd64-3.9 -DPYTHON_EXECUTABLE=c:\users\saketh\appdata\local\programs\python\python39\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\build\lib.win-amd64-3.9 -A x64'
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:5 (message):

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    You must use Visual Studio to build a python extension on windows.  If you
    are getting this error it means you have not installed Visual C++.  Note
    that there are many flavors of Visual Studio, like Visual Studio for C#
    development.  You need to install Visual Studio for C++.

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\setup.py", line 222, in <module>
      setup(
    File "c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\setup.py", line 134, in run
      self.build_extension(ext)
    File "C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\setup.py", line 171, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "c:\users\saketh\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=c:\\users\\saketh\\appdata\\local\\programs\\python\\python39\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\build\\lib.win-amd64-3.9', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib, pywarping
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saketh\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\setup.py'"'"'; __file__='"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\saketh\AppData\Local\Temp\pip-record-j6g7aj6l\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\saketh\appdata\local\programs\python\python39\Include\dlib'
         cwd: C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\
    Complete output (60 lines):
    running install
    running build
    running build_py
    package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
    Invoking CMake setup: 'cmake C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\build\lib.win-amd64-3.9 -DPYTHON_EXECUTABLE=c:\users\saketh\appdata\local\programs\python\python39\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\build\lib.win-amd64-3.9 -A x64'
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:5 (message):

      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      You must use Visual Studio to build a python extension on windows.  If you
      are getting this error it means you have not installed Visual C++.  Note
      that there are many flavors of Visual Studio, like Visual Studio for C#
      development.  You need to install Visual Studio for C++.

      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    -- Configuring incomplete, errors occurred!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\setup.py", line 222, in <module>
        setup(
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\setup.py", line 134, in run
        self.build_extension(ext)
      File "C:\Users\saketh\AppData\Local\Temp\pip-install-n2rkpdbi\dlib_d0a2d4f321944269b438c57829027f12\setup.py", line 171, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "c:\users\saketh\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=c:\\users\\saketh\\appdata\\local\\programs\\python\\python39\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\build\\lib.win-amd64-3.9', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\saketh\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\setup.py'"'"'; __file__='"'"'C:\\Users\\saketh\\AppData\\Local\\Temp\\pip-install-n2rkpdbi\\dlib_d0a2d4f321944269b438c57829027f12\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\saketh\AppData\Local\Temp\pip-record-j6g7aj6l\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\saketh\appdata\local\programs\python\python39\Include\dlib' Check the logs for full command output.`

**Comment by dopevog** [comment]
Hey.  Do you have the Visual C++ installed as `dlib` seems to need that on windows. If not download it from [here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0). 

Thanks for checking out `PyWarping`!

**Comment by SG-SakethGupta** [comment]
Woah thank you so much :D

**Comment by dopevog** [comment]
No Problem 😊
